# Generated by Django 3.2.4 on 2022-07-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20220304_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPhaseTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('SINGLE', '单选题'), ('MULTIPLE', '多选题'), ('COMPLETION', '填空题')], max_length=20, verbose_name='题目类型')),
                ('question_id', models.IntegerField(default=0, verbose_name='题号')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
                ('question', models.TextField(verbose_name='题目')),
                ('option_A', models.TextField(blank=True, null=True, verbose_name='选项A')),
                ('option_B', models.TextField(blank=True, null=True, verbose_name='选项B')),
                ('option_C', models.TextField(blank=True, null=True, verbose_name='选项C')),
                ('option_D', models.TextField(blank=True, null=True, verbose_name='选项D')),
                ('option_E', models.TextField(blank=True, null=True, verbose_name='选项E')),
                ('answer', models.TextField(verbose_name='问题答案')),
                ('explain', models.TextField(blank=True, default='无', null=True, verbose_name='答案解析')),
                ('remarks', models.TextField(blank=True, default='无', null=True, verbose_name='备注')),
                ('difficulty', models.IntegerField(default=0, verbose_name='难度')),
                ('discipline', models.CharField(default='无', max_length=40, verbose_name='所属学科')),
            ],
        ),
    ]
